### ISSUE TITLE
Question about post-firmware outcome with JTAGulator

### ISSUE THREAD

**Issue by CyberTecky** [grandideastudio/jtagulator#25]
FW EEPROM 1.6 Loaded with an odd output effect in the Parallax Simple Terminal where the JTAGulator banner seems condensed and compacted.  Not sure if this is a result on my end?   In addition, just need to verify that available the commands are all listed properly - They seem different that the tutorial you did a few years back:

See snapshots of banner and command output (Attch)
![banner_output](https://user-images.githubusercontent.com/39555877/48667667-c8d30000-ea98-11e8-81bd-c7c2c4f194ce.png)
![version_help_commands](https://user-images.githubusercontent.com/39555877/48667668-c8d30000-ea98-11e8-9dbf-9bccc3e773e8.png)

Thanks!

CJ

**Comment by joegrand** [comment]
It's possible that you just have a different font selected, which is causing the condensed view. You should be able to get rid of the extra linefeed between each line by unchecking the Line Feed option under Preferences. See attached images of the settings I use in Parallax Serial Terminal.

Regarding the commands, what you're seeing is the latest. The videos/tutorials used an older version of firmware and I've revised the menu system since then. Eventually, I'll make an updated video and documentation explaining functionality of the new commands. 

Enjoy!

Joe

<img width="442" alt="screen shot 2018-11-17 at 9 31 06 pm" src="https://user-images.githubusercontent.com/4250259/48667984-d4322580-eab0-11e8-9721-82d5b8211bed.png">

<img width="1440" alt="screen shot 2018-11-17 at 8 54 19 pm" src="https://user-images.githubusercontent.com/4250259/48667985-da280680-eab0-11e8-807e-7adfb3df25d5.png">

**Comment by joegrand** [comment]
It looks like the condensed view is caused by some change in font or a line length/wrap setting. Perhaps it has to do with the default system font within Windows that Parallax Serial Terminal is using. It's purely aesthetic. You should be able to get rid of the extra linefeed between each line by unchecking the Line Feed option under Preferences. See attached images of the settings I use in Parallax Serial Terminal.

Regarding the commands, what you're seeing is the latest. The videos/tutorials used an older version of firmware and I've revised the menu system since then. Eventually, I'll make an updated video and documentation explaining functionality of the new commands.

Enjoy!

Joe

<img width="442" alt="screen shot 2018-11-17 at 9 31 06 pm" src="https://user-images.githubusercontent.com/4250259/48668018-810ca280-eab1-11e8-97f7-ea6aaf0228a5.png">

<img width="444" alt="screen shot 2018-11-17 at 9 31 12 pm" src="https://user-images.githubusercontent.com/4250259/48668019-85d15680-eab1-11e8-8f8d-90348cac0fa8.png">

**Comment by CyberTecky** [comment]
Well Done Joe!

I made those changes that you suggested and everything seems to line up now.  Looks like I'm ready to begin this new adventure working with the JTAGulator!

CJ
