### ISSUE TITLE
Baud rate confusion

### ISSUE THREAD

**Issue by BG7YWL** [grandideastudio/jtagulator#35]
I tried to make jtagulator 2 times, the first time I tried it was a green PCB, all functions are normal. The second time I tried to make a better black PCB, I encountered some problems.
![微信图片_20200427113452](https://user-images.githubusercontent.com/9145406/80355253-6c3d5c80-88aa-11ea-8cbc-9597b279ff04.jpg)

green PCB：
![Snipaste_2020-04-27_11-37-05](https://user-images.githubusercontent.com/9145406/80355397-a0b11880-88aa-11ea-9b5e-eb17b61e232e.png)

black PCB：
1. The UART pin cannot be recognized normally, and the hardware cannot be connected through the UART.
2. CH0-CH7 cannot recognize JTAG hardware, CH8-CH23 is normal!
![1](https://user-images.githubusercontent.com/9145406/80355590-dc4be280-88aa-11ea-8aad-c752fc5c8bbe.png)
![2](https://user-images.githubusercontent.com/9145406/80355607-df46d300-88aa-11ea-810b-4a24e8368205.png)
![3](https://user-images.githubusercontent.com/9145406/80355620-e372f080-88aa-11ea-9dcd-c806fb531a3f.png)

I tried to swap the green and black PCB chips. Everything in green is normal, and black is still wrong.
How can I debug the hardware?

**Comment by joegrand** [comment]
My guess is that this is a hardware issue related to components or connectivity. I would visually check all component orientations and soldering quality.

I've just completed an updated and clarified version of the test procedure. It is available at my main JTAGulator page (http://www.grandideastudio.com/jtagulator/). If and where your board fails during the process should help you narrow down the root cause. 

Unfortunately, I don't have enough bandwidth to support people's custom boards. Given the inconsistencies of component sourcing, PCB fabrication, and build skill/assembly quality, there are simply too many unknowns to remotely solve hardware problems. Our official JTAGulator units are sold through Parallax and are fully testing during manufacturing - those are fully supported. If you find that this is an issue related only to firmware, you can re-open the issue and provide more details about your environment, including a description of your target hardware and high-resolution photos showing connections/wiring.
