### ISSUE TITLE
CC26X0 - No target device(s) found

### ISSUE THREAD

**Issue by daniel-rome** [grandideastudio/jtagulator#52]
Hi, 

I have been trying Jtagulator with a couple of CC2640R2F devices and I have always got the "No target device(s) found!" message (tried different scans and even setting the pins). The JTAG port is working as I am able to connect/debug it by using the buspirate. I only connected the TMS, TCLK, TDO and TDI (+GND) pins to the Jtagulator but was not able to find the pins by using it. I tried this with different Jtagulator firmware's (including the last one 1.11) but had no luck. 

Could it be that this is not following standards but buspirate is able to work with it? I already checked some existing issues but nothing related. 

Many thanks,

**Comment by joegrand** [comment]
Since you're seeing a response with the Bus Pirate, that means it's likely related to #3 either due to external pull resistors or something internal with the chip that causes incompatibility with the JTAGulator's front end protection circuitry. The [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) has some suggestions of workarounds, but unfortunately the JTAGulator's current hardware design isn't compatible with all types of devices.
